import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { IngredientsProvider } from "./_contexts/IngredientsContext";
import { RecipesProvider } from "./_contexts/RecipesContext";

const inter = Inter({
  weight: "variable",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <IngredientsProvider>
          <RecipesProvider>{children}</RecipesProvider>
        </IngredientsProvider>
      </body>
    </html>
  );
}
